// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeforeClose(arg1) {
  return window['go']['predict']['App']['BeforeClose'](arg1);
}

export function DomReady(arg1) {
  return window['go']['predict']['App']['DomReady'](arg1);
}

export function Predict(arg1) {
  return window['go']['predict']['App']['Predict'](arg1);
}

export function RegisterEnums(arg1) {
  return window['go']['predict']['App']['RegisterEnums'](arg1);
}

export function RegisterStructs(arg1) {
  return window['go']['predict']['App']['RegisterStructs'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['predict']['App']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['predict']['App']['Startup'](arg1);
}
