// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {client} from '../models';

export function BeforeClose(arg1:context.Context):Promise<boolean>;

export function DomReady(arg1:context.Context):Promise<void>;

export function Predict(arg1:Array<number>):Promise<client.IResponse>;

export function RegisterEnums(arg1:Array<any>):Promise<Array<any>>;

export function RegisterStructs(arg1:Array<any>):Promise<Array<any>>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
